# Site settings
title: Jekyll shop powered by Snipcart
email: geeks@snipcart.com
description: Here's a quick demo showing the integration between Snipcart and Jekyll. We hope you like it!
baseurl: "/altwalker/snipcart-jekyll-ecommerce-demo" # the subpath of your site, e.g. /blog/
url: "https://altwalker.github.io" # the base hostname & protocol for your site
twitter_username: Snipcart
github_username:  Snipcart
api_key: OWU0NmY0MTYtMzlkYi00ZTk2LWI5OGUtNmMyYTdmNTE1ZGI3NjM2ODQ2MTMxNTgzNDk0ODg0

# Build settings
markdown: kramdown
collections:
  products:
    output: true
